[2025-04-15T12:44:22.245+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T12:44:22.423+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-15T07:21:00+00:00 [queued]>
[2025-04-15T12:44:22.502+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-15T07:21:00+00:00 [queued]>
[2025-04-15T12:44:22.509+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-15T12:44:22.974+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-04-15 07:21:00+00:00
[2025-04-15T12:44:23.053+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4168) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-15T12:44:23.076+0000] {standard_task_runner.py:72} INFO - Started process 4170 to run task
[2025-04-15T12:44:23.066+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'scheduled__2025-04-15T07:21:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/lead_data_pipeline.py', '--cfg-path', '/tmp/tmp0w4f086r']
[2025-04-15T12:44:23.084+0000] {standard_task_runner.py:105} INFO - Job 115: Subtask run_dbt_trusted
[2025-04-15T12:44:23.630+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-15T07:21:00+00:00 [running]> on host c0ac39583bd8
[2025-04-15T12:44:25.207+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T07:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-15T07:21:00+00:00'
[2025-04-15T12:44:25.222+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-15T12:44:25.453+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-15T12:44:25.463+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-04-15T12:44:25.513+0000] {subprocess.py:86} INFO - Output:
[2025-04-15T12:44:25.555+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-04-15T12:44:25.568+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-04-15T12:59:47.782+0000] {job.py:229} INFO - Heartbeat recovered after 903.70 seconds
[2025-04-15T12:59:50.336+0000] {subprocess.py:93} INFO - [0m12:59:50  Running with dbt=1.8.0
[2025-04-15T12:59:50.983+0000] {subprocess.py:93} INFO - [0m12:59:50  Registered adapter: postgres=1.8.2
[2025-04-15T12:59:51.825+0000] {subprocess.py:93} INFO - [0m12:59:51  Found 9 models, 10 sources, 428 macros
[2025-04-15T12:59:51.831+0000] {subprocess.py:93} INFO - [0m12:59:51
[2025-04-15T12:59:52.071+0000] {subprocess.py:93} INFO - [0m12:59:52  Concurrency: 1 threads (target='dev')
[2025-04-15T12:59:52.072+0000] {subprocess.py:93} INFO - [0m12:59:52
[2025-04-15T12:59:52.089+0000] {subprocess.py:93} INFO - [0m12:59:52  1 of 4 START sql table model lead_trusted.non_pii_data ......................... [RUN]
[2025-04-15T13:12:33.095+0000] {job.py:229} INFO - Heartbeat recovered after 743.86 seconds
[2025-04-15T13:28:23.745+0000] {job.py:229} INFO - Heartbeat recovered after 930.09 seconds
[2025-04-15T14:13:34.022+0000] {job.py:229} INFO - Heartbeat recovered after 2689.33 seconds
[2025-04-15T14:29:29.076+0000] {job.py:229} INFO - Heartbeat recovered after 929.19 seconds
[2025-04-15T14:45:19.561+0000] {job.py:229} INFO - Heartbeat recovered after 904.16 seconds
[2025-04-15T15:00:46.716+0000] {job.py:229} INFO - Heartbeat recovered after 906.62 seconds
[2025-04-15T15:14:35.862+0000] {job.py:229} INFO - Heartbeat recovered after 808.54 seconds
[2025-04-15T15:15:13.054+0000] {subprocess.py:93} INFO - [0m15:15:13  1 of 4 OK created sql table model lead_trusted.non_pii_data .................... [[32mSELECT 21225910[0m in 8120.93s]
[2025-04-15T15:15:13.097+0000] {subprocess.py:93} INFO - [0m15:15:13  2 of 4 START sql table model lead_trusted.payment_data ......................... [RUN]
[2025-04-15T15:30:24.566+0000] {job.py:229} INFO - Heartbeat recovered after 907.47 seconds
[2025-04-15T15:46:14.408+0000] {job.py:229} INFO - Heartbeat recovered after 929.25 seconds
[2025-04-15T15:50:30.843+0000] {job.py:229} INFO - Heartbeat recovered after 215.18 seconds
[2025-04-15T15:50:35.464+0000] {subprocess.py:93} INFO - [0m15:50:35  2 of 4 OK created sql table model lead_trusted.payment_data .................... [[32mSELECT 3977366[0m in 2122.36s]
[2025-04-15T15:50:35.467+0000] {subprocess.py:93} INFO - [0m15:50:35  3 of 4 START sql table model lead_trusted.pii_data ............................. [RUN]
[2025-04-15T16:06:08.002+0000] {job.py:229} INFO - Heartbeat recovered after 932.13 seconds
[2025-04-15T16:11:53.821+0000] {job.py:229} INFO - Heartbeat recovered after 304.61 seconds
[2025-04-15T16:15:36.943+0000] {job.py:229} INFO - Heartbeat recovered after 181.77 seconds
[2025-04-15T16:31:13.811+0000] {job.py:229} INFO - Heartbeat recovered after 931.85 seconds
[2025-04-15T16:39:02.720+0000] {job.py:229} INFO - Heartbeat recovered after 394.19 seconds
[2025-04-15T18:26:42.102+0000] {job.py:229} INFO - Heartbeat recovered after 6449.06 seconds
[2025-04-15T18:56:39.641+0000] {job.py:229} INFO - Heartbeat recovered after 1777.34 seconds
[2025-04-15T18:57:23.669+0000] {job.py:229} INFO - Heartbeat recovered after 18.66 seconds
[2025-04-15T18:57:37.583+0000] {subprocess.py:93} INFO - [0m18:57:37  3 of 4 OK created sql table model lead_trusted.pii_data ........................ [[32mSELECT 21225910[0m in 11222.10s]
[2025-04-15T18:57:37.593+0000] {subprocess.py:93} INFO - [0m18:57:37  4 of 4 START sql table model lead_trusted.technical_data ....................... [RUN]
[2025-04-16T00:00:12.937+0000] {job.py:229} INFO - Heartbeat recovered after 18154.06 seconds
[2025-04-16T00:00:21.783+0000] {subprocess.py:93} INFO - [0m00:00:21  4 of 4 OK created sql table model lead_trusted.technical_data .................. [[32mSELECT 3154094[0m in 18164.19s]
[2025-04-16T00:00:21.818+0000] {subprocess.py:93} INFO - [0m00:00:21
[2025-04-16T00:00:21.819+0000] {subprocess.py:93} INFO - [0m00:00:21  Finished running 4 table models in 11 hours 0 minutes and 29.98 seconds (39629.98s).
[2025-04-16T00:00:21.921+0000] {subprocess.py:93} INFO - [0m00:00:21
[2025-04-16T00:00:21.923+0000] {subprocess.py:93} INFO - [0m00:00:21  [32mCompleted successfully[0m
[2025-04-16T00:00:21.924+0000] {subprocess.py:93} INFO - [0m00:00:21
[2025-04-16T00:00:21.932+0000] {subprocess.py:93} INFO - [0m00:00:21  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-04-16T00:02:41.846+0000] {job.py:229} INFO - Heartbeat recovered after 143.87 seconds
[2025-04-16T00:02:43.147+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-16T00:02:43.792+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-16T00:02:43.801+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=run_dbt_trusted, run_id=scheduled__2025-04-15T07:21:00+00:00, execution_date=20250415T072100, start_date=20250415T124422, end_date=20250416T000243
[2025-04-16T00:02:44.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T00:02:44.152+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-16T00:02:44.190+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
