[2025-04-13T10:52:55.451+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T10:52:55.468+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-04-13T10:52:54.500458+00:00 [queued]>
[2025-04-13T10:52:55.475+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-04-13T10:52:54.500458+00:00 [queued]>
[2025-04-13T10:52:55.476+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-13T10:52:55.490+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_raw_data> on 2025-04-13 10:52:54.500458+00:00
[2025-04-13T10:52:55.495+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T10:52:55.497+0000] {standard_task_runner.py:72} INFO - Started process 254 to run task
[2025-04-13T10:52:55.497+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'extract_raw_data', 'manual__2025-04-13T10:52:54.500458+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/lead_data_pipeline.py', '--cfg-path', '/tmp/tmp_lc0swfx']
[2025-04-13T10:52:55.499+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask extract_raw_data
[2025-04-13T10:52:55.547+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-04-13T10:52:54.500458+00:00 [running]> on host 414b1c8e5c9f
[2025-04-13T10:52:55.621+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T10:52:54.500458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T10:52:54.500458+00:00'
[2025-04-13T10:52:55.623+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-13T10:52:55.639+0000] {lead_data_pipeline.py:144} INFO - Started batch processing for 2025-04-13.
[2025-04-13T10:52:55.639+0000] {lead_data_pipeline.py:34} INFO - Created synthetic data for RO country code.
[2025-04-13T10:53:23.737+0000] {lead_data_pipeline.py:101} INFO - Written 100372 records to the CSV file.
[2025-04-13T10:53:26.011+0000] {lead_data_pipeline.py:117} INFO - Added UUID to the dataset.
[2025-04-13T10:53:26.020+0000] {lead_data_pipeline.py:152} INFO - Finished batch processing 2025-04-13.
[2025-04-13T10:53:26.020+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-13T10:53:26.032+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-13T10:53:26.032+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=extract_raw_data, run_id=manual__2025-04-13T10:52:54.500458+00:00, execution_date=20250413T105254, start_date=20250413T105255, end_date=20250413T105326
[2025-04-13T10:53:26.092+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T10:53:26.116+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-13T10:53:26.118+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
